### ISSUE TITLE
Campfire for decoration purposes

### ISSUE THREAD

**Issue by SuisArt** [UghZan/campfireOverhaul#1]
This is not an issue its an suggestion/idea, so far i dont have any issues with this mod... It would be nice to have an item or an other mehtod to light the campfire indefinintly, for decoration purposes (for example: chimney smoke). Maybe Nether-Star and Flint in Hands? Or a special block under the Campfire? (The block should not be too "cheap").

**Comment by UghZan** [comment]
Yeah, that's a good idea. I will think of something

**Comment by UghZan** [comment]
Now right-clicking a campfire with Dragon's Breath will make it burn forever. I'm not entirely sure that it should be this expensive, but you may use soul campfires for it, as they are infinite by default (because, you know, soulflame, nether magic and stuff)
