### ISSUE TITLE
The campfire caused the game to crash

### ISSUE THREAD

**Issue by nitbe** [UghZan/campfireOverhaul#14]
[latest.log](https://github.com/UghZan/campfireOverhaul/files/7372648/latest.log)
The game log shows that there is a problem with the campfire

**Comment by nitbe** [comment]
> 你能提供更多信息吗？你是自己点了篝火还是在世界上找到的？你有没有改变任何配置？你对篝火做过什么（放食物，用铲子把它灭掉等）？当你用它做某事时它会崩溃还是只是随机的？

#Enable/disable infinite life time for indirectly placed campfires (e.g. worldgen, other mods mechanics).
	worldgenCampfiresInfinite = false
I modified this, in the game I have not synthesized the campfire, just walking around the game crashed

**Comment by UghZan** [comment]
Fixed in new version. Should be available on curseforge soon!
