### ISSUE TITLE
[Suggestion] Allow the player to set their spawn at campfires.

### ISSUE THREAD

**Issue by Corvus20** [UghZan/campfireOverhaul#4]
If a player shift right clicks (or some other hotkey, idk), they can set a secondary spawn point at the campfire. Upon dying, the player returns to the campfire, but with the fire burnt out.  If you die once the campfire is burnt out, you will respawn at your primary spawn point (your bed).

**Comment by UghZan** [comment]
Hey, that's a great idea! I like it. Will try to do that.

**Comment by UghZan** [comment]
Yeah, it's a bit too much for my coding skills at the moment. I sure will add this, but on a later date.
