### ISSUE TITLE
Infernal Expansion Glowlight campfire compat?

### ISSUE THREAD

**Issue by pm065** [UghZan/campfireOverhaul#6]
Would it be possible to do this, seeing as you've managed to overhaul the EE ender campfire?
No rush, just letting you know it exists :D

**Comment by UghZan** [comment]
Never heard of that mod, I'll check it out! Will do.

**Comment by UghZan** [comment]
It seems like they are using non-default class for their campfires, so my mod's changes doesn't really work with them. Probably too much trouble to try and fix it from my side, sorry.
