### ISSUE TITLE
Change recipe overrides to check if endergetic/campful is installed

### ISSUE THREAD

**Issue by G-Stav** [UghZan/campfireOverhaul#7]
Right now it causes a bit of spam in the error log, was able to circumvent it by just replacing the recipes. But it would be a nice QoL for it to check if the mods are loaded before changing recipes that... well aren't there.

**Comment by UghZan** [comment]
I would like to add this, but couldn't find a way for now. I will put it on a TO-DO list, but for now the manual deleting is the only way.
