### ISSUE TITLE
Compatibility with No Tree Punching

### ISSUE THREAD

**Issue by WesternFreak** [UghZan/campfireOverhaul#8]
The [No Tree Punching](https://www.curseforge.com/minecraft/mc-mods/no-tree-punching) mod removes the campfire crafting recipe and instead uses in-world crafting: dropping sticks and a log, then using a Fire Starter on the dropped items, which then spawns a campfire on the world, already lit (which makes total sense) but that also burns forever, bypassing any configured fuel requirement of Campfire Overhaul:

![image](https://user-images.githubusercontent.com/4205706/115990573-e38bf600-a5bb-11eb-8988-edc3b2005fec.png)

![image](https://user-images.githubusercontent.com/4205706/115990574-e8e94080-a5bb-11eb-9d16-7cc52c879527.png)

The testing was done with the following mods:

![image](https://user-images.githubusercontent.com/4205706/115970096-4045cd00-a538-11eb-9aa9-19d2d98d7175.png)

I understand that since NTP changes the way to obtain a campfire it might not be possible to fix this on Campfire Overhaul's side of things, it's still worth reporting as I understand it.

**Comment by UghZan** [comment]
Thank you for a detailed bug report! I will look into it and see if I can fix it on my side.

**Comment by UghZan** [comment]
It seems like I have no way of making it compatible from my side. I will add a config option for disabling infinite life time on world-placed campfires, but that would screw with village-placed campfires, so you'll have to "pick your poison".
